### ISSUE TITLE
Comments css verwijderen

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#10]
https://github.com/sjagoori/web-app-from-scratch-2021/blob/3dd3060b7a8b6df502937167fe49313ebdf2182e/static/css/styles.css#L13

Staat er nog een in.

**Comment by sjagoori** [comment]
[a7225b6](https://github.com/sjagoori/web-app-from-scratch-2021/commit/a7225b6a0fe28801b6e0e98ebdffb6a889e904a8)
