### ISSUE TITLE
Namen van kleuren geven

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#11]
https://github.com/sjagoori/web-app-from-scratch-2021/blob/3dd3060b7a8b6df502937167fe49313ebdf2182e/static/js/modules/colors.js#L2

Wellicht een idee om in een comment erboven even alle kleuren toe te lichten. Geen idee in hoeverre het relevant is om te weten, maar ik weet nu niet om welke kleuren dit gaat.

**Comment by sjagoori** [comment]
![image](https://user-images.githubusercontent.com/64035489/108529036-58993180-72d4-11eb-8257-c8f340753963.png)
[ecd071b](https://github.com/sjagoori/web-app-from-scratch-2021/commit/ecd071b799355c394417ed021724336456d50792)
