### ISSUE TITLE
Consistentie 🙂

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#12]
https://github.com/sjagoori/web-app-from-scratch-2021/blob/3dd3060b7a8b6df502937167fe49313ebdf2182e/static/js/modules/rounding.js#L6

Enige plek in heel de code waar je semicolon gebruikt

**Comment by sjagoori** [comment]
![image](https://user-images.githubusercontent.com/64035489/108528836-21c31b80-72d4-11eb-9c62-beaed879fbb9.png)
