### ISSUE TITLE
Ordenen?

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#13]
Waar worden de cryptocurrencies op geordend? Er staat `by market cap in biggest-to-smallest order.`, maar dat is niet het geval? Staat er cache op? BNB is inmiddels nummer drie met een waarde van $250, terwijl die bij jou nog $59.15 is.

**Comment by sjagoori** [comment]
Heb je gelijk in, heb het meegenomen in [6fa0b19](https://github.com/sjagoori/web-app-from-scratch-2021/commit/6fa0b19f6f2919888c87087f80bcf880a33ee406)
