### ISSUE TITLE
Extra enter

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#2]
https://github.com/sjagoori/web-app-from-scratch-2021/blob/8dae0430fe37ebe69f4c5523c50464aece6e92cf/spa/static/js/modules/api.js#L5

Dit valt wel in de categorie mierenneuken, maar volgens mij hoort er (officieel) een enter tussen params en de rest van de comment te zitten. Correct me if I'm wrong, haha. Heeft weer met readability te maken.

**Comment by jochemvogel** [comment]
Dus dan zo:

```
/**
 * Function makes an API calls and caches them if they're not cached before
 * 
 * @param {String} url API endpoint
 * @param {Object} header Header params
 */
```

ipv

```
/**
 * Function makes an API calls and caches them if they're not cached before
 * @param {String} url API endpoint
 * @param {Object} header Header params
 */
```

**Comment by sjagoori** [comment]
Ik ben het met je eens 😁 ik (probeer) aan te houden wat ze bij [jsdoc.app](jsdoc.app/) schrijven, daar doen ze het zonder enter!

**Comment by jochemvogel** [comment]
> Ik ben het met je eens 😁 ik (probeer) aan te houden wat ze bij [jsdoc.app](jsdoc.app/) schrijven, daar doen ze het zonder enter!

Oké, prima. Dan heeft het vast te maken met de code style van sommige bedrijven. Thanks, ik zal die link eens op m'n gemak checken.
