### ISSUE TITLE
Functie(s) kleiner maken

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#3]
https://github.com/sjagoori/web-app-from-scratch-2021/blob/8dae0430fe37ebe69f4c5523c50464aece6e92cf/spa/static/js/modules/render.js#L10

Je moet zelf maar even kijken of je het met mij eens bent, maar ik vind de functie nogal lang. Zou je deze niet kunnen opsplitsen. 

Je zou ook kunnen kijken naar het schrijven van HTML in JS. Maakt het volgens mij ook een stuk korter.

Moet je maar even Googelen naar **Write JS in HTML JSX** oid als je niet weet hoe of wat. Kom je wel uit.

Ik heb het zelf [zo](https://github.com/jochemvogel/web-app-from-scratch-2021/blob/4c81c498df2030ac43533d4d2f079d44d8247608/js/app.js#L49) gedaan

**Comment by jochemvogel** [comment]
Zelfde geldt overigens ook voor [deze functie ](https://github.com/sjagoori/web-app-from-scratch-2021/blob/8dae0430fe37ebe69f4c5523c50464aece6e92cf/spa/static/js/modules/render.js#L51). Is in mijn optiek echt te lang.

**Comment by sjagoori** [comment]
terwijl innterhtml makkelijker schrijft en leest, overtreft de createElement het op elk ander punt, zie [[1]](https://www.javascripttutorial.net/javascript-dom/javascript-innerhtml-vs-createelement) [[2]](https://stackoverflow.com/questions/2946656/advantages-of-createelement-over-innerhtml/2947012#2947012) en [mdn](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Manipulating_documents#active_learning_basic_dom_manipulation)). Op deze manier is het niet alleen sneller maar ook makkelijker uit te breiden met (complexere) DOM manipulatie

**Comment by jochemvogel** [comment]
@sjagoori Mee eens. Goed punt. Alleen sommige functies zijn nog steeds 50+ regels (met name de render functies). Wat ik meer probeerde te zeggen was: wellicht kun je de functies nog opsplitsen in kleinere functies.
