### ISSUE TITLE
test.js verwijderen

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#4]
Wellicht kan `test.js` nog weg. Doet naast een `console.log` niet zo veel.

Als het wel wat doet, dan kun je misschien de naam aan passen. Is nu een beetje raar.

Dat was het laatste. Voor de rest kan ik niet zo veel vinden 😄

**Comment by sjagoori** [comment]
Good call, deleted! [053716a](https://github.com/sjagoori/web-app-from-scratch-2021/commit/053716aa106fae57ea4eaa1f69c3e85b7e4d2c93)
