### ISSUE TITLE
Code review week 1

### ISSUE THREAD

**Issue by RobinFrugte97** [sjagoori/web-app-from-scratch-2021#6]
Yo Shabier,

Goeie overview pagina! Je hebt zelfs al detail pagina's, lekker bezig man.
Goed begin van je readme ook.

Je app.js ziet er super clean uit. Modules en al! Lekker functioneel ook.

Je comments met param's zijn ook heel chill!

Je bent al bezig met localStorage ook, heel goed. 

Paar dingetjes:

- Er staan nog een paar dingetjes van de fork in je repo. Je zou course, examples en docs weg kunnen gooien, dat maakt het wat cleaner en voorkomt verwarring.

- Vul je readme aan met dingen zoals een screenshot van je overview pagina, een gedeelte over wat voor data je binnen krijgt (Je linkt wel naar docs van de api, maar het kan prettig zijn om een kleine inkijk te geven in wat voor data je gebruikt, hoe het eruit ziet etc.).

- Misschien kun je je functies iets verder opdelen in andere functies. Je functies in render.js zijn super lang.

Verder weinig te melden, het ziet er naar uit dat je het wel snapt ;)
Kijk of je jezelf verder kunt uitdagen als we met routing en templating beginnen de komende weken. Misschien kun je je eigen router of templating engine schrijven. Als je meer uitdaging zoekt en je hebt zelf een idee, stel het gerust voor!

**Comment by sjagoori** [comment]
- [ ] extra bestanden uit de fork halen 
- [ ] schreenshots, api docs & transformatie toevoegen aan de readme 
- [x] #3
