### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by solideagency** [sjagoori/web-app-from-scratch-2021#7]
Ontzettend goed bezig! Tof hoever je al bent en hoe netjes de code is. Ik zie hier iemand die consistent werkt, nice :)

Een paar tips:

- Kun je jezelf nog wat meer uitdagen in het concept? Hoe kan je deze app complexer maken? Er is een probleem rondom crypto currency wat je zou kunnen oplossen met jouw app? Bijvoorbeeld... zouden we kunnen voorspellen wat over 10 jaar de top crypto's zijn, of kun je misschien een vergelijking maken tussen crypto en aandelen?
- Voeg hier en daar code comments toe, wat doet welke functie en waarom. Bijvoorbeeld: `({ ...infoList.data.data, merged }, delete infoList.data.data.merged)` 
- Nice grid in CSS!
- Complimenten voor de modules en hoe clean dit is opgezet!
- Is het bouwen van je eigen template engine een idee?

**Comment by sjagoori** [comment]
added comments [063cba5](https://github.com/sjagoori/web-app-from-scratch-2021/commit/063cba5854cd63c662f48dba68a305b3b6a5b283)
