### ISSUE TITLE
.vscode folder

### ISSUE THREAD

**Issue by jochemvogel** [sjagoori/web-app-from-scratch-2021#9]
Niet echt een issue, maar is het niet beter om deze in je `.gitignore` te zetten? Lijkt mij dat het jouw voorkeur is, toch?

**Comment by sjagoori** [comment]
[0a6b44](https://github.com/sjagoori/web-app-from-scratch-2021/commit/0a6b44acfcb1fd81d06bd80901c018145a5b343a)

Onderbouwing:
[Should I commit the .vscode folder to source control?](https://stackoverflow.com/a/47668283)
